using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace GameplayTags.Editor
{
    internal static class GameplayTagCodeGenerator
    {
        private static readonly HashSet<string> Keywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        public static void Generate(GameplayTagSettings settings)
        {
            if (settings == null)
                throw new ArgumentNullException("settings");

            GameplayTagEditorUtility.InitializeManager(settings, true);
            string path = settings.GeneratedCodePath;
            if (string.IsNullOrEmpty(path) || !path.Replace('\\', '/').StartsWith("Assets/", StringComparison.Ordinal))
            {
                EditorUtility.DisplayDialog(
                    "Gameplay Tags",
                    "Generated code path must be inside Assets/.",
                    "OK");
                return;
            }

            string className = SanitizeIdentifier(settings.GeneratedClassName, "GameplayTags");
            string namespaceName = SanitizeNamespace(settings.GeneratedNamespace);
            string contentHash = settings.ComputeContentHash().ToString("X8");
            var usedIdentifiers = new HashSet<string>(StringComparer.Ordinal);
            usedIdentifiers.Add("ContentHash");
            usedIdentifiers.Add(className);
            var builder = new StringBuilder(4096);
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// Generated by ZFramework Gameplay Tags. Do not edit manually.");
            builder.Append("// ContentHash: 0x").Append(contentHash).AppendLine();
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("using GameplayTags;");
            builder.AppendLine();

            if (!string.IsNullOrEmpty(namespaceName))
            {
                builder.Append("namespace ").Append(namespaceName).AppendLine();
                builder.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(namespaceName) ? string.Empty : "    ";
            builder.Append(indent).Append("public static class ").Append(className).AppendLine();
            builder.Append(indent).AppendLine("{");
            string memberIndent = indent + "    ";
            builder.Append(memberIndent)
                .Append("public const uint ContentHash = 0x")
                .Append(contentHash)
                .AppendLine("u;");
            builder.AppendLine();

            IReadOnlyList<GameplayTagDefinition> definitions = settings.Tags;
            if (settings.IncludeImplicitParentTagsInGeneratedCode)
            {
                // 隐式父级没有定义条目，注释只能从显式定义里查。
                var comments = new Dictionary<string, string>(StringComparer.Ordinal);
                for (int i = 0; i < definitions.Count; i++)
                    comments[definitions[i].Name] = definitions[i].DevComment;

                IReadOnlyList<GameplayTag> tags = GameplayTagManager.GetAllTags();
                for (int i = 0; i < tags.Count; i++)
                {
                    comments.TryGetValue(tags[i].Name, out string comment);
                    AppendTagMember(builder, memberIndent, usedIdentifiers, tags[i].Name, comment);
                }
            }
            else
            {
                for (int i = 0; i < definitions.Count; i++)
                    AppendTagMember(builder, memberIndent, usedIdentifiers, definitions[i].Name, definitions[i].DevComment);
            }

            builder.Append(indent).AppendLine("}");
            if (!string.IsNullOrEmpty(namespaceName))
                builder.AppendLine("}");

            string directory = Path.GetDirectoryName(path).Replace('\\', '/');
            GameplayTagEditorUtility.EnsureAssetDirectory(directory);
            File.WriteAllText(path, builder.ToString(), new UTF8Encoding(false));
            AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();
        }

        private static void AppendTagMember(
            StringBuilder builder,
            string indent,
            HashSet<string> usedIdentifiers,
            string tagName,
            string devComment)
        {
            // "A.B" 和 "A_B" 会清洗成同一个标识符，靠递增后缀区分；标签本身按序数排序，所以后缀是稳定的。
            string baseIdentifier = SanitizeIdentifier(tagName.Replace('.', '_'), "Tag");
            string identifier = baseIdentifier;
            int collisionIndex = 2;
            while (!usedIdentifiers.Add(identifier))
                identifier = baseIdentifier + "_" + collisionIndex++;

            if (!string.IsNullOrEmpty(devComment))
            {
                builder.Append(indent).Append("/// <summary>")
                    .Append(EscapeXml(devComment)).AppendLine("</summary>");
            }
            builder.Append(indent)
                .Append("public static readonly GameplayTag ")
                .Append(identifier)
                .Append(" = GameplayTagManager.RequestTag(\"")
                .Append(EscapeString(tagName))
                .AppendLine("\", true);");
        }

        private static string SanitizeNamespace(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            string[] segments = value.Split('.');
            for (int i = 0; i < segments.Length; i++)
                segments[i] = SanitizeIdentifier(segments[i], "Generated");
            return string.Join(".", segments);
        }

        private static string SanitizeIdentifier(string value, string fallback)
        {
            if (string.IsNullOrEmpty(value))
                return fallback;

            var builder = new StringBuilder(value.Length + 1);
            for (int i = 0; i < value.Length; i++)
            {
                char character = value[i];
                if (char.IsLetterOrDigit(character) || character == '_')
                    builder.Append(character);
                else
                    builder.Append('_');
            }

            if (builder.Length == 0)
                builder.Append(fallback);
            if (char.IsDigit(builder[0]))
                builder.Insert(0, '_');

            string identifier = builder.ToString();
            if (Keywords.Contains(identifier))
                identifier = "@" + identifier;
            return identifier;
        }

        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string EscapeXml(string value)
        {
            return value.Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\r", " ")
                .Replace("\n", " ");
        }
    }
}
