<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Optimize>true</Optimize>
    <SourceRoot Condition="'$(SourceRoot)' == ''">..</SourceRoot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(SourceRoot)/Runtime/**/*.cs" />
    <Compile Include="$(SourceRoot)/Editor/**/*.cs" />
    <Compile Include="UnityStubs.cs" />
    <Compile Include="Extended.cs" />
  </ItemGroup>
</Project>
