using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace GameplayTags
{
    /// <summary>
    /// Generates cached handles from semantic assembly attributes. A generated assembly
    /// cannot know the final cross-assembly runtime ID space, so each accessor resolves
    /// its name once at type initialization and returns the cached handle thereafter.
    /// </summary>
    [Generator]
    public sealed class GameplayTagSourceGenerator : ISourceGenerator
    {
        private static readonly DiagnosticDescriptor InvalidName = new DiagnosticDescriptor(
            "GT001", "Invalid gameplay tag name", "Gameplay tag name '{0}' requires nonempty dot-separated labels containing only letters, digits or underscores",
            "GameplayTags", DiagnosticSeverity.Error, true);

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            INamedTypeSymbol attributeType = context.Compilation.GetTypeByMetadataName("GameplayTags.GameplayTagAttribute");
            if (attributeType == null)
                return;

            var root = new TagNode("AllGameplayTags", null, string.Empty);
            foreach (AttributeData attribute in context.Compilation.Assembly.GetAttributes())
            {
                context.CancellationToken.ThrowIfCancellationRequested();
                if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, attributeType))
                    continue;

                string name = attribute.ConstructorArguments.Length == 0
                    ? null : attribute.ConstructorArguments[0].Value as string;
                // A named property argument overrides the constructor, exactly as the
                // runtime attribute does. Constants, aliases and qualified names have
                // already been resolved by Roslyn rather than parsed as source text.
                foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
                    if (argument.Key == "TagName")
                        name = argument.Value.Value as string;

                if (!IsValidName(name))
                {
                    Location location = attribute.ApplicationSyntaxReference == null ? Location.None
                        : attribute.ApplicationSyntaxReference.GetSyntax(context.CancellationToken).GetLocation();
                    context.ReportDiagnostic(Diagnostic.Create(InvalidName, location, name ?? "<null>"));
                    continue;
                }
                AddTag(root, name);
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("// Cached names intentionally resolve against the complete immutable runtime registry.");
            source.AppendLine("namespace GameplayTags");
            source.AppendLine("{");
            GenerateClasses(source, root);
            source.AppendLine("}");
            context.AddSource("GameplayTags.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        }

        private static void AddTag(TagNode root, string name)
        {
            TagNode current = root;
            int start = 0;
            while (true)
            {
                int dot = name.IndexOf('.', start);
                int end = dot < 0 ? name.Length : dot;
                string label = name.Substring(start, end - start);
                if (!current.Children.TryGetValue(label, out TagNode next))
                {
                    string prefix = dot < 0 ? name : name.Substring(0, end);
                    next = new TagNode(label, current, prefix);
                    current.Children.Add(label, next);
                }
                current = next;
                if (dot < 0)
                    return;
                start = dot + 1;
            }
        }

        private static void GenerateClasses(StringBuilder source, TagNode root)
        {
            root.Identifier = "AllGameplayTags";
            var pending = new Stack<Frame>();
            pending.Push(new Frame(root, 1, false));
            while (pending.Count != 0)
            {
                Frame frame = pending.Pop();
                TagNode node = frame.Node;
                string indent = new string(' ', frame.Depth * 4);
                if (frame.Close)
                {
                    source.Append(indent).AppendLine("}");
                    continue;
                }

                source.Append(indent).Append("internal static partial class ").AppendLine(node.Identifier);
                source.Append(indent).AppendLine("{");
                if (node.Parent != null)
                {
                    source.Append(indent).AppendLine("    private static readonly global::GameplayTags.GameplayTag s_Tag;");
                    // An explicit static constructor suppresses beforefieldinit. Without
                    // it, the CLR can resolve a field before an earlier-looking explicit
                    // GameplayTagManager.Initialize call in the same caller method.
                    source.Append(indent).Append("    static ").Append(node.Identifier).AppendLine("()");
                    source.Append(indent).AppendLine("    {");
                    source.Append(indent).Append("        s_Tag = global::GameplayTags.GameplayTagManager.RequestTag(")
                        .Append(SymbolDisplay.FormatLiteral(node.FullName, true)).AppendLine(");");
                    source.Append(indent).AppendLine("    }");
                    source.Append(indent).AppendLine("    public static global::GameplayTags.GameplayTag Get() => s_Tag;");
                }
                pending.Push(new Frame(node, frame.Depth, true));

                // SortedDictionary supplies ordinal siblings; reverse the push order
                // to emit deterministic preorder independent of source-file ordering.
                var children = new List<TagNode>(node.Children.Values);
                for (int i = children.Count - 1; i >= 0; --i)
                {
                    TagNode child = children[i];
                    child.Identifier = GetIdentifier(child.Label, node.Identifier);
                    pending.Push(new Frame(child, frame.Depth + 1, false));
                }
            }
        }

        private static string GetIdentifier(string label, string enclosingIdentifier)
        {
            const string encodedPrefix = "__gt_";
            string identifier;
            bool keyword = SyntaxFacts.GetKeywordKind(label) != SyntaxKind.None ||
                SyntaxFacts.GetContextualKeywordKind(label) != SyntaxKind.None;
            if (!label.StartsWith(encodedPrefix, StringComparison.Ordinal) && label != "Get" && label != "s_Tag" &&
                (keyword || SyntaxFacts.IsValidIdentifier(label)))
                identifier = keyword ? "@" + label : label;
            else
                identifier = Encode(label);

            string enclosingName = enclosingIdentifier[0] == '@' ? enclosingIdentifier.Substring(1) : enclosingIdentifier;
            string identifierName = identifier[0] == '@' ? identifier.Substring(1) : identifier;
            if (identifierName == enclosingName)
                identifier = Encode(label) + "__child";
            return identifier;
        }

        // Reserving/encoding the prefix itself makes escaping injective: a leading-digit
        // label cannot collide with a literal tag whose spelling resembles its encoding.
        private static string Encode(string label)
        {
            const string hex = "0123456789abcdef";
            var text = new StringBuilder("__gt_");
            for (int i = 0; i < label.Length; ++i)
            {
                int c = label[i];
                text.Append(hex[(c >> 12) & 15]);
                text.Append(hex[(c >> 8) & 15]);
                text.Append(hex[(c >> 4) & 15]);
                text.Append(hex[c & 15]);
            }
            return text.ToString();
        }

        private static bool IsValidName(string name)
        {
            if (string.IsNullOrEmpty(name))
                return false;
            bool needsCharacter = true;
            for (int i = 0; i < name.Length; ++i)
            {
                char c = name[i];
                if (c == '.')
                {
                    if (needsCharacter)
                        return false;
                    needsCharacter = true;
                }
                else if (c == '_' || char.IsLetterOrDigit(c))
                    needsCharacter = false;
                else
                    return false;
            }
            return !needsCharacter;
        }

        private sealed class TagNode
        {
            internal TagNode(string label, TagNode parent, string fullName)
            {
                Label = label;
                Parent = parent;
                FullName = fullName;
            }

            internal readonly string Label;
            internal readonly TagNode Parent;
            internal readonly string FullName;
            internal readonly SortedDictionary<string, TagNode> Children = new SortedDictionary<string, TagNode>(StringComparer.Ordinal);
            internal string Identifier;
        }

        private readonly struct Frame
        {
            internal Frame(TagNode node, int depth, bool close)
            {
                Node = node;
                Depth = depth;
                Close = close;
            }
            internal readonly TagNode Node;
            internal readonly int Depth;
            internal readonly bool Close;
        }
    }
}
